### ISSUE TITLE
Publish documentation so it is easy to understand without technical details

### ISSUE THREAD

**Issue by brylie** [efel85/TOMP-API#51]
Currently, the documentation is merged and rendered in Swagger UI, and immediately shows technical details. This can make it difficult to form a concept of the APIs as a whole, before diving into relevant technical details. In essence, the technical details should perhaps be secondary, allowing the reader to understand the overall picture first, e.g. how it relates to business activities, etc.

Please consider providing a higher-level narrative describing the purpose of the API and sub-components.

To this end, there are a couple of tools that balance the narrative and technical details, even allowing the API specifications to be divided into multiple files and including content pages:

- [DapperDox](http://dapperdox.io/)

**Comment by efel85** [comment]
Thanks Brylie, I indeed had the same discussion with Tim from Skedgo. I will try to provide this high-level narrative similar to how he has presented the Skedgo Booking API.

**Comment by drtimcooper** [comment]
Edoardo has done a great overview document.  It does a good job of explaining the scope and the workflow.  This will be received well by business people who want to know if the standard does what they need.

As a developer, I'd also want the bridge between these concepts, and REST PUT/POST/GET/etc calls, with a few examples.  The full swagger documentation can give the full details, but would it be worth putting a couple of JSON examples in the high level document?  So I know that "this is the JSON if I'm in the planning stage", "this is the JSON if I'm committing to a booking"...

Do you think, when Edoardo's high level document is complete, and the swagger is complete, that I could read them both and quickly write code to make and manage bookings?  Without having to read and understand the entire detailed documentation first?

Because this will be the very first thing I want to do:  write a sample client and server using the API to connect to someone else's sample client and server, initially for the most basic example of a taxi booking.  If I can get a simple taxi booking working then I can build upwards from there and learn more about the standard as my brain can cope with the new information.  (I seem to have more of a focus on "other people driving you" rather than "assets"....I think TfNSW are equally interested in both...could I implement taxis before city-bikes or will the standard be defined in the opposite sequence?)

**Comment by efel85** [comment]
Will be included in a TOMP-API for Dummies document as proposed by @drtimcooper in issue #52

**Comment by drtimcooper** [comment]
Is this a duplicate?  Should we close either this issue or #52?

**Comment by brylie** [comment]
I think the suggestion for using [DapperDox](http://dapperdox.io/) should please be kept in the context, regardless of which issue remains open :-)

**Comment by edwinvandenbelt** [comment]
DapperDox only visualises the yaml in a nice way. It doesn't give you extra functionality.

**Comment by efel85** [comment]
Aligned with issue #52, so this issue can be closed.
