### ISSUE TITLE
How are MSP and TO's going to authenticate each other?

### ISSUE THREAD

**Issue by efel85** [efel85/TOMP-API#7]
Submitted by Pim van Toolen

**Comment by skinkie** [comment]
The BV Nederland solved this chicken-egg via eHerkenning ;-) A more sensible approach is a directory with public keys, which are used for message signing. You might be interested in the workings of https://en.wikipedia.org/wiki/XML_Signature

**Comment by efel85** [comment]
Accept might play a role in this as they are the ones issuing IDs to TOs and MSPs

**Comment by efel85** [comment]
Accept has approved their authentication method to be used within the TOMP-API. Details should be available in [https://github.com/efel85/TOMP-API/blob/master/documents/Information%20document%20for%20testing%20parties%20within%20MaaS%20at%20Accept%20Institute%20V0.8.pdf](url)

**Comment by pimmeh** [comment]
The URL doesn't work @efel85 
The question I had was more in the technical solution part. We currently use JSON Web Tokens where the authorisation key is in supplied in the header. If you have the correct URL, maybe I can loop it up whether that is documented there or not.

I would say, this is required for version 1.1, otherwise we have an API, but no common way for MP and TO to use it between them,

**Comment by efel85** [comment]
> The URL doesn't work @efel85
> 
The document is placed in our Github code repository, under 'documents'. The link pointed there!

**Comment by Tjalle** [comment]
Url in the Master Branch : 
https://github.com/efel85/TOMP-API/tree/master/documents/Information document for testing parties within MaaS at Accept Institute V0.8.pdf

**Comment by efel85** [comment]
Authentication method is included in header (#48)
